# Generated by Django 4.2.1 on 2023-06-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_name_author_fname_remove_book_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_instance',
            old_name='unique_Id',
            new_name='unique_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter date of birth of Author', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Enter date of death of Author', null=True, verbose_name='Died'),
        ),
        migrations.AlterField(
            model_name='author',
            name='fname',
            field=models.CharField(help_text='Enter first name of Author', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='lname',
            field=models.CharField(help_text='Enter last name of Author', max_length=50),
        ),
        migrations.AlterField(
            model_name='book_instance',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_instance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On load'), ('a', 'Available'), ('r', 'Reversed')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter book language ', max_length=35),
        ),
    ]
