# Generated by Django 4.2.1 on 2023-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_unique_id_book_instance_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, default=1, help_text='Enter date of birth of Author'),
            preserve_default=False,
        ),
    ]
